In [27]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [16]:
data=pd.read_csv('/content/drive/MyDrive/mu-sigma/adult.csv')
data


age          workclass  fnlwgt    education  education-num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week         country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       salary  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [17]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'country', 'salary'],
      dtype='object')

In [19]:
data.describe()

age        fnlwgt  education-num  capital-gain  capital-loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours-per-week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loss    32561 non-null  int64 
 12  hours-per-week  32561 non-null  int64 
 13  country         32561 non-null  object
 14  salary          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [20]:
data.isnull().sum()


age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
country           0
salary            0
dtype: int64

In [38]:
adult['workclass'].value_counts()

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1298
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: workclass, dtype: int64

In [69]:
print('Continous variables in the dataset are: ')
cont=[]
for i in data.columns:
  if data[i].dtype=='int64':
    cont.append(i)
    print(i,end=', ')
print('\n\nCategorical variable in the dataset are: ')
catg=[]
for i in data.columns:
  if data[i].dtype=='O':
    catg.append(i)
    print(i,end=',  ')

Continous variables in the dataset are: 
age, fnlwgt, education-num, capital-gain, capital-loss, hours-per-week, 

Categorical variable in the dataset are: 
workclass,  education,  marital-status,  occupation,  relationship,  race,  sex,  country,  salary,  

In [70]:
cont

['age',
 'fnlwgt',
 'education-num',
 'capital-gain',
 'capital-loss',
 'hours-per-week']

In [71]:
catg


['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'country',
 'salary']

In [72]:
data['salary'].describe()

count      32561
unique         2
top        <=50K
freq       24720
Name: salary, dtype: object

In [73]:
data['salary'].value_counts()

 <=50K    24720
 >50K      7841
Name: salary, dtype: int64

In [74]:
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(data,test_size=0.30,random_state=42)

In [75]:
train_set

age          workclass  fnlwgt      education  education-num  \
19749   34   Self-emp-not-inc   56460        HS-grad              9   
1216    48   Self-emp-not-inc  243631   Some-college             10   
27962   23          State-gov   56402   Some-college             10   
23077   56          Local-gov  255406        HS-grad              9   
10180   17            Private  297246           11th              7   
...    ...                ...     ...            ...            ...   
29802   47            Private  359461      Bachelors             13   
5390    31            Private  147215           12th              8   
860     18            Private  216284           11th              7   
15795   50   Self-emp-not-inc   54261        HS-grad              9   
23654   34       Self-emp-inc  127651      Bachelors             13   

            marital-status        occupation    relationship  \
19749   Married-civ-spouse   Farming-fishing            Wife   
1216    Married-civ-spouse      Craft-repair         Husband   
27962   Married-civ-spouse    Prof-specialty         Husband   
23077             Divorced   Exec-managerial   Not-in-family   
10180        Never-married   Priv-house-serv       Own-child   
...                    ...               ...             ...   
29802   Married-civ-spouse      Craft-repair         Husband   
5390              Divorced     Other-service       Unmarried   
860          Never-married      Adm-clerical       Own-child   
15795   Married-civ-spouse   Farming-fishing         Husband   
23654             Divorced   Farming-fishing   Not-in-family   

                      race      sex  capital-gain  capital-loss  \
19749                White   Female             0          2179   
1216    Amer-Indian-Eskimo     Male          7688             0   
27962                White     Male             0             0   
23077                White   Female             0             0   
10180                White   Female             0             0   
...                    ...      ...           ...           ...   
29802                White     Male             0             0   
5390                 White   Female             0             0   
860                  White   Female             0             0   
15795                White     Male             0             0   
23654                White     Male             0             0   

       hours-per-week         country  salary  
19749              12   United-States   <=50K  
1216               40   United-States    >50K  
27962              30   United-States   <=50K  
23077              40   United-States   <=50K  
10180               9   United-States   <=50K  
...               ...             ...     ...  
29802              40   United-States   <=50K  
5390               21   United-States   <=50K  
860                20   United-States   <=50K  
15795              84   United-States   <=50K  
23654              60   United-States   <=50K  

[22792 rows x 15 columns]

In [76]:
x_train=train_set.drop('salary',axis=1)
y_train=train_set['salary']

In [77]:
num_data=x_train[cont]
num_data

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week
19749   34   56460              9             0          2179              12
1216    48  243631             10          7688             0              40
27962   23   56402             10             0             0              30
23077   56  255406              9             0             0              40
10180   17  297246              7             0             0               9
...    ...     ...            ...           ...           ...             ...
29802   47  359461             13             0             0              40
5390    31  147215              8             0             0              21
860     18  216284              7             0             0              20
15795   50   54261              9             0             0              84
23654   34  127651             13             0             0              60

[22792 rows x 6 columns]

In [78]:
catg


['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'country',
 'salary']

In [87]:
cat_column=['workclass','education','marital-status','occupation','relationship','race','sex','country']
cat_value=x_train[cat_column]
cat_value

workclass      education       marital-status  \
19749   Self-emp-not-inc        HS-grad   Married-civ-spouse   
1216    Self-emp-not-inc   Some-college   Married-civ-spouse   
27962          State-gov   Some-college   Married-civ-spouse   
23077          Local-gov        HS-grad             Divorced   
10180            Private           11th        Never-married   
...                  ...            ...                  ...   
29802            Private      Bachelors   Married-civ-spouse   
5390             Private           12th             Divorced   
860              Private           11th        Never-married   
15795   Self-emp-not-inc        HS-grad   Married-civ-spouse   
23654       Self-emp-inc      Bachelors             Divorced   

             occupation    relationship                 race      sex  \
19749   Farming-fishing            Wife                White   Female   
1216       Craft-repair         Husband   Amer-Indian-Eskimo     Male   
27962    Prof-specialty         Husband                White     Male   
23077   Exec-managerial   Not-in-family                White   Female   
10180   Priv-house-serv       Own-child                White   Female   
...                 ...             ...                  ...      ...   
29802      Craft-repair         Husband                White     Male   
5390      Other-service       Unmarried                White   Female   
860        Adm-clerical       Own-child                White   Female   
15795   Farming-fishing         Husband                White     Male   
23654   Farming-fishing   Not-in-family                White     Male   

              country  
19749   United-States  
1216    United-States  
27962   United-States  
23077   United-States  
10180   United-States  
...               ...  
29802   United-States  
5390    United-States  
860     United-States  
15795   United-States  
23654   United-States  

[22792 rows x 8 columns]

In [89]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder=OneHotEncoder()
cat_data_1hot=cat_encoder.fit_transform(cat_value).toarray()
cat_data_1hot

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [86]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
num_data_scaled=ss.fit_transform(num_data)
num_data_scaled

array([[-0.33477088, -1.26129178, -0.42321894, -0.14634899,  5.13611784,
        -2.30985135],
       [ 0.69122318,  0.51064242, -0.03537743,  0.92974178, -0.21992119,
        -0.03129473],
       [-1.14090907, -1.26184086, -0.03537743, -0.14634899, -0.21992119,
        -0.84506495],
       ...,
       [-1.50733552,  0.25175037, -1.19890196, -0.14634899, -0.21992119,
        -1.65883517],
       [ 0.83779376, -1.28210955, -0.42321894, -0.14634899, -0.21992119,
         3.54929422],
       [-0.33477088, -0.58733178,  1.12814709, -0.14634899, -0.21992119,
         1.5962457 ]])

In [96]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
num_pipeline=Pipeline([
                       ('std scaler',StandardScaler())
])
from sklearn.compose import ColumnTransformer
full_pipeline = ColumnTransformer([
("num", num_pipeline, cont),
("cat", OneHotEncoder(),cat_column ),
])

In [98]:
data_prepared=full_pipeline.fit_transform(x_train).toarray()
data_prepared

array([[-0.33477088, -1.26129178, -0.42321894, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.69122318,  0.51064242, -0.03537743, ...,  1.        ,
         0.        ,  0.        ],
       [-1.14090907, -1.26184086, -0.03537743, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-1.50733552,  0.25175037, -1.19890196, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.83779376, -1.28210955, -0.42321894, ...,  1.        ,
         0.        ,  0.        ],
       [-0.33477088, -0.58733178,  1.12814709, ...,  1.        ,
         0.        ,  0.        ]])

In [99]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y_label=lb.fit_transform(y_train)
y_label

array([0, 1, 0, ..., 0, 0, 0])

In [105]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
tree=DecisionTreeClassifier()
forest=RandomForestClassifier()



In [109]:
from sklearn.model_selection import GridSearchCV
param_grid = [
{'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]},
{'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]},
]
grid_search = GridSearchCV(forest, param_grid, cv=5,
scoring='f1')

In [110]:
grid_search.fit(data_prepared,y_label)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4],
                          'n_estimators': [3, 10]}],
             scoring='f1')

In [112]:
final_model=grid_search.best_estimator_

In [113]:
y_pred=final_model.predict(data_prepared)


In [114]:
from sklearn.metrics import f1_score,accuracy_score
f1=f1_score(y_label,y_pred)
f1

0.9964613011523455

In [117]:
acc=accuracy_score(y_label,y_pred)
acc

0.9982888732888733